// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vguwaajipdwopytacgqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndXdhYWppcGR3b3B5dGFjZ3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTU5MjksImV4cCI6MjA2Mzk5MTkyOX0.1IUNFlolJSbyp_4-RDggC1iogBDQNIT09Vu-ALZ42eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);